package: clear_content
version: '2.0.0-beta'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/clear_content
kurzbeschreibung: 'AddOn um REDAXO Inhalte zu löschen.'

page:
    hidden: true

pages:
    system/clear_content:
        title: 'translate:clear_content'
        perm: admin
        icon:  rex-icon fa fa-trash
        pjax: true

requires:
    redaxo: '^5.2'
    packages:
        media_manager: '^2.0.1'
    php:
        version: '>=7.3'